name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm ci && npm run build && touch build/.nojekyll
        PUBLIC_URL: /hunger-games
